st="mallikarjun sure123"
print(st.isalnum())
print(st.capitalize())
print(st.casefold())
print(st.count('a'))
print(st.find('3'))
print(st.index('i'))
print(st.isalpha())
print(st.isupper())
print(st.islower())